import json
import os
import sys
from pathlib import Path
from typing import Any

# Standard config paths
CONFIG_DIR = Path.home() / ".wims"
SERVER_CONFIG_FILE = CONFIG_DIR / "server.json"
CLIENT_CONFIG_FILE = CONFIG_DIR / "config.json"


def load_config() -> dict[str, Any]:
    """
    Load configuration.
    Prioritizes ~/.wims/server.json (auto-generated by core).
    Falls back to ~/.wims/config.json (manual client config).
    Returns a dictionary with 'api_url' and 'api_key'.
    Exits if config is missing or invalid.
    """
    config = {}

    # Ensure directory exists
    if not CONFIG_DIR.exists():
        try:
            CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            print(f"Error creating config directory {CONFIG_DIR}: {e}")
            sys.exit(1)

    # Try server.json first (Zero-conf)
    if SERVER_CONFIG_FILE.exists():
        try:
            with open(SERVER_CONFIG_FILE) as f:
                server_conf = json.load(f)
                # Construct URL from host/port if not explicitly set
                host = server_conf.get("host", "127.0.0.1")
                port = server_conf.get("port", 8000)
                protocol = "http"  # Default for local
                config["api_url"] = f"{protocol}://{host}:{port}"
                config["api_key"] = server_conf.get("api_key")
        except Exception as e:
            print(f"Warning: Failed to read {SERVER_CONFIG_FILE}: {e}")

    # Try config.json (Manual override)
    if CLIENT_CONFIG_FILE.exists():
        try:
            with open(CLIENT_CONFIG_FILE) as f:
                client_conf = json.load(f)
                # Client config overrides server config
                config.update(client_conf)
        except json.JSONDecodeError:
            print(f"Error: Invalid JSON in {CLIENT_CONFIG_FILE}")
            sys.exit(1)

    # Check Environment Variable
    if not config.get("api_key"):
        config["api_key"] = os.environ.get("WIMS_API_KEY")

    # Validate required fields
    if not config.get("api_key"):
        print("Error: 'api_key' not found in configuration.")
        print(f"Checked: {SERVER_CONFIG_FILE}, {CLIENT_CONFIG_FILE}, and WIMS_API_KEY env var.")
        print("Please run the wims-core server to generate a config, or create a config file manually.")
        sys.exit(1)

    # Set defaults
    if "api_url" not in config:
        config["api_url"] = "http://localhost:8000"

    # Remove trailing slash from api_url if present
    config["api_url"] = config["api_url"].rstrip("/")

    return config
